name: rag-fed
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl=13.1.78=he1e9d2a_0
  - cuda-cccl_win-64=13.1.78=hc667259_0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.80=hde976d8_0
  - cuda-opencl-dev=13.1.80=hde976d8_0
  - cuda-profiler-api=13.1.80=h4ecfac6_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - debugpy=1.8.19=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py311haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py311h8598115_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.1.34=hde976d8_0
  - libcurand-dev=10.4.1.34=hde976d8_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=py311haa95532_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - requests=2.32.5=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - bitsandbytes==0.49.0
      - blinker==1.9.0
      - brotli==1.2.0
      - build==1.3.0
      - cachetools==6.2.4
      - chromadb==1.4.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.76.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - docker==7.1.0
      - durationpy==0.10
      - faiss-cpu==1.13.2
      - fastapi==0.128.0
      - fastjsonschema==2.21.2
      - fed-rag==0.1
      - ffmpy==1.0.0
      - flask==3.1.2
      - flask-cors==6.0.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.45.0
      - googleapis-common-protos==1.72.0
      - gradio==6.2.0
      - gradio-client==2.0.2
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.0
      - groovy==0.1.2
      - groq==0.37.1
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huey==2.5.5
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jiter==0.12.0
      - joblib==1.5.3
      - json-repair==0.55.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==1.2.0
      - langchain-chroma==1.1.0
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.6
      - langchain-experimental==0.4.1
      - langchain-groq==1.1.1
      - langchain-huggingface==1.2.0
      - langchain-openai==1.1.6
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.1
      - langsmith==0.6.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mlflow==3.8.1
      - mlflow-skinny==3.8.1
      - mlflow-tracing==3.8.1
      - mmh3==5.2.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - numpy==1.26.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==1.109.1
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - pdfminer-six==20251107
      - pdfplumber==0.11.8
      - pfzy==0.3.4
      - plotly==6.5.1
      - posthog==5.4.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pyparsing==3.3.1
      - pypdf==6.5.0
      - pypdfium2==5.2.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.11.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentence-transformers==5.2.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - starlette==0.50.0
      - sympy==1.13.1
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.21.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uvicorn==0.40.0
      - waitress==3.0.2
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\rubi6\anaconda3\envs\rag-fed
